title: "Pod 4.1.X"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  Aaron's portfolio website
baseurl: "/" 
url: "ajlevine.github.io/portfolio/" 
twitter_username: Alayelbot
github_username:  ajlevine

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
